export const SET_COURSE_VIDEOS = 'SET_COURSE_VIDEOS';

const dummyVideos = [
  {
    id: 1,
    title: "What is AI Engineer?",
    professor: "Jay Feng",
    category: "AI",
    videoUrl: "https://www.youtube.com/watch?v=o0OczKvQ_is",
    posterUrl: "https://i.ytimg.com/vi/o0OczKvQ_is/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBD7a1cpo2VI9mQfD9fYi8JNc08WA",
    description: "Nikhil was the second AI engineer at Perplexity—a startup now worth $10 billion. But here's the twist: he didn't even know what PyTorch was.In this video, we break down what AI engineers really do today, why companies are hiring them like crazy, and how you can become one—even without a PhD.Watch the full interview and learn how AI engineering is transforming modern software development. 🚀Get started as an AI engineer with Outskill: !",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 35,
    duration: "4.5 total hours",
    instructorName: "Devonne Wallbridge",
    instructorRole: "Web Developer, Designer, and Teacher",
    instructorAvatar: "https://i.pravatar.cc/100",
    rating: 4.5,
    reviewCount: 1200,
    progress: 45,
  },
  {
    id: 2,
    title: "UI/UX Basic Fundamentals",
    professor: "Devonne Wallbridge",
    category: "QA",
    videoUrl: "https://www.youtube.com/watch?v=u8vMu7viCm8&t=2643s",
    posterUrl: "https://i.ytimg.com/vi/u8vMu7viCm8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwV3fh71b6oql4ekdHTW9LX5BR3Q",
    description: "Learn web design in 1 hour with 25+ simple-to-use rules and guidelines — tons of amazing web design resources included!",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 19,
    duration: "1.5 total hours",
    instructorName: "Reyand Oneil",
    instructorRole: "Web Developer, QA Automation, and Teacher",
    instructorAvatar: "https://i.pravatar.cc/100",
    rating: 4.5,
    reviewCount: 4500,
    progress: 30,
  },
  {
    id: 3,
    title: "Express.js Fundamentals",
    professor: "Devonne Wallbridge",
    category: "UI/UX",
    videoUrl: "https://www.youtube.com/watch?v=CnH3kAXSrmU",
    posterUrl: "https://i.ytimg.com/vi/CnH3kAXSrmU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAJsbboLRs1YG_7RvbGSlM5r8qn5w",
    description: "Get started with the most popular web framework for Node.js.",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 19,
    duration: "0.3 total hours",
    instructorName: "Devonne Wallbridge",
    instructorRole: "Web Developer, Designer, and Teacher",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Devonne",
    rating: 4.5,
    reviewCount: 1435,
    progress: 75,
  },
  {
    id: 4,
    title: "n8n Quick Start Tutorial: Build Your First Workflow [2025]",
    professor: "Devonne Wallbridge",
    category: "AI",
    videoUrl: "https://www.youtube.com/watch?v=4cQWJViybAQ&list=PLlET0GsrLUL5HKJk1rb7t32sAs_iAlpZe",
    posterUrl: "https://i.ytimg.com/vi/4cQWJViybAQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB0Mnoah3yoJPej5O_ZxfUxGpATbw",
    description: " the conceptual foundations you need to know to build powerful n8n workflows from scratch.",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 19,
    duration: "1.5 total hours",
    instructorName: "Devonne Wallbridge",
    instructorRole: "Web Developer, Designer, and Teacher",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Devonne",
    rating: 4.5,
    reviewCount: 1200,
    progress: 10,
  },
  {
    id: 5,
    title: "Level up your UI design skills Start learning Design Systems",
    professor: "Devonne Wallbridge",
    category: "UI/UX",
    videoUrl: "https://www.youtube.com/watch?v=R2Bsn1WJkUw",
    posterUrl: "https://i.ytimg.com/vi/R2Bsn1WJkUw/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLABxwhmxeJsrV_P77_OheJ5A_UKVQ",
    description: "Learning to approach your designs using the Atomic Design methodology is such a game-changing skill. This is the foundation of becoming a design systems designer which any team larger than 10 people will be running off of. You can't learn to design inside of a design system without first understanding how to structure your designs from an architectural level. In this video I break down how Atomic Design works and how to break design components into elements that can be re-used across your entire ui/ux design.",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 19,
    duration: "1.5 total hours",
    instructorName: "Devonne Wallbridge",
    instructorRole: "Web Developer, Designer, and Teacher",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Devonne",
    rating: 4.5,
    reviewCount: 1200,
    progress: 90,
  },
  {
    id: 6,
    title: "Video Production Basics",
    professor: "Devonne Wallbridge",
    category: "UI/UX",
    videoUrl: "https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4",
    posterUrl: "https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg",
    description: "Learn web design in 1 hour with 25+ simple-to-use rules and guidelines — tons of amazing web design resources included!",
    skillLevel: "All Levels",
    students: 38815,
    languages: "English",
    captions: true,
    lectures: 19,
    duration: "1.5 total hours",
    instructorName: "Devonne Wallbridge",
    instructorRole: "Web Developer, Designer, and Teacher",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Devonne",
    rating: 4.5,
    reviewCount: 1200,
    progress: 60,
  },
  {
    id: 7,
    title: "React Advanced Patterns",
    professor: "Sarah Johnson",
    category: "Frontend",
    videoUrl: "https://www.youtube.com/watch?v=9xhKH43llhU",
    posterUrl: "https://i.ytimg.com/vi/9xhKH43llhU/hq720.jpg",
    description: "Master advanced React patterns including hooks, context, and performance optimization techniques.",
    skillLevel: "Intermediate",
    students: 25680,
    languages: "English",
    captions: true,
    lectures: 28,
    duration: "3.2 total hours",
    instructorName: "Sarah Johnson",
    instructorRole: "Senior React Developer",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    rating: 4.7,
    reviewCount: 890,
    progress: 25,
  },
  {
    id: 8,
    title: "Python for Data Science",
    professor: "Dr. Michael Chen",
    category: "Data Science",
    videoUrl: "https://www.youtube.com/watch?v=8DvywoWv6fI",
    posterUrl: "https://i.ytimg.com/vi/8DvywoWv6fI/hq720.jpg",
    description: "Comprehensive introduction to Python programming for data analysis and machine learning.",
    skillLevel: "Beginner",
    students: 45230,
    languages: "English",
    captions: true,
    lectures: 42,
    duration: "5.8 total hours",
    instructorName: "Dr. Michael Chen",
    instructorRole: "Data Science Professor",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    rating: 4.6,
    reviewCount: 2100,
    progress: 80,
  },
  {
    id: 9,
    title: "Cybersecurity Fundamentals",
    professor: "Alex Rivera",
    category: "Security",
    videoUrl: "https://www.youtube.com/watch?v=3Kq1MIfTWCE",
    posterUrl: "https://i.ytimg.com/vi/3Kq1MIfTWCE/hq720.jpg",
    description: "Learn the basics of cybersecurity, including encryption, network security, and ethical hacking.",
    skillLevel: "All Levels",
    students: 18950,
    languages: "English",
    captions: true,
    lectures: 31,
    duration: "4.1 total hours",
    instructorName: "Alex Rivera",
    instructorRole: "Cybersecurity Expert",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    rating: 4.4,
    reviewCount: 650,
    progress: 15,
  },
  {
    id: 10,
    title: "Mobile App Development with Flutter",
    professor: "Emma Wilson",
    category: "Mobile",
    videoUrl: "https://www.youtube.com/watch?v=VPvVD8t02U8",
    posterUrl: "https://i.ytimg.com/vi/VPvVD8t02U8/hq720.jpg",
    description: "Build cross-platform mobile applications using Flutter and Dart programming language.",
    skillLevel: "Beginner",
    students: 32100,
    languages: "English",
    captions: true,
    lectures: 38,
    duration: "6.5 total hours",
    instructorName: "Emma Wilson",
    instructorRole: "Mobile Developer",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    rating: 4.8,
    reviewCount: 1450,
    progress: 50,
  },
  {
    id: 11,
    title: "DevOps with Docker and Kubernetes",
    professor: "James Park",
    category: "DevOps",
    videoUrl: "https://www.youtube.com/watch?v=3c-iBn73dDE",
    posterUrl: "https://i.ytimg.com/vi/3c-iBn73dDE/hq720.jpg",
    description: "Master containerization and orchestration with Docker and Kubernetes for modern deployment.",
    skillLevel: "Intermediate",
    students: 28750,
    languages: "English",
    captions: true,
    lectures: 45,
    duration: "7.2 total hours",
    instructorName: "James Park",
    instructorRole: "DevOps Engineer",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    rating: 4.5,
    reviewCount: 980,
    progress: 35,
  },
  {
    id: 12,
    title: "Blockchain Development",
    professor: "Lisa Zhang",
    category: "Blockchain",
    videoUrl: "https://www.youtube.com/watch?v=gyMwXuJUbPQ",
    posterUrl: "https://i.ytimg.com/vi/gyMwXuJUbPQ/hq720.jpg",
    description: "Learn to build decentralized applications using Ethereum, smart contracts, and Web3 technologies.",
    skillLevel: "Intermediate",
    students: 15680,
    languages: "English",
    captions: true,
    lectures: 33,
    duration: "5.4 total hours",
    instructorName: "Lisa Zhang",
    instructorRole: "Blockchain Developer",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    rating: 4.3,
    reviewCount: 720,
    progress: 70,
  },
];

export const setCourseVideos = () => ({
  type: SET_COURSE_VIDEOS,
  payload: dummyVideos,
});
